language: node_js
node_js:
    - "node"

env:
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN

install:
    - npm install
    - npm install karma-cli webpack typescript codeclimate-test-reporter grunt --global

cache:
    directories:
        - "node_modules"

script:
    - npm test
    - tsc ts/helpers.ts --outDir ./js/ --target es5

after_success:
  - find ./coverage -name "lcovonly" -exec cp {} ./lcovonly \;
  - grunt coveralls
