language: node_js
node_js:
    - "node"

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN

install:
    - npm install
    - npm install karma-cli webpack typescript codeclimate-test-reporter --global

cache:
    directories:
        - "node_modules"

script:
    - npm test
    - tsc ts/asp-net-core-url-compiler.ts --outDir ./js/

after_success:
  - find ./coverage -name "lcovonly" -exec cp {} ./lcov.info \;
  - codeclimate-test-reporter < lcov.info
